# Generated by Django 6.1.2 on 2026-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Material', 'Material'), ('Tarea', 'Tarea'), ('Evaluación', 'Evaluación')], default='Material', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('enlace', models.URLField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material Educativo',
                'verbose_name_plural': 'Materiales Educativos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Alerta de Riesgo', 'verbose_name_plural': 'Alertas de Riesgo'},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-fecha'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tutor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tutor_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tutor_telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
